apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ .Values.peerAuthentication.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  mtls:
    mode: {{ .Values.peerAuthentication.mode }}