apiVersion: v1
kind: Service
metadata:
  name: {{ include "muffin-wallet.fullname" . }}-log
  labels:
    {{- include "muffin-wallet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "muffin-wallet.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80